### ISSUE TITLE
add "supported by INNOQ" in footer

### ISSUE THREAD

**Issue by gernotstarke** [arc42/status.arc42.org-site#18]
and, at the same time, try a centered footer, as in [datamesh-architecture.com](http://datamesh-architecture.com/)

take the graphical logo from the datamesh site.

**Comment by Per-Starke** [comment]
Done for this site, please have a look if you like it like this. The size of the supported-by-innnoq image is responsive, being smaller on smaller screens.

Shall I also do this on other sites?

<img width="1440" alt="status_footer" src="https://github.com/arc42/status.arc42.org-site/assets/7078370/b916e730-756f-4943-bac6-692e2458b32e">

**Comment by gernotstarke** [comment]
perfect.
